#JWT
jwt:
  token:
    expire: 10

spring:
  application:
    name: labboot-back

  output:
    ansi:
      enabled: always

  # 讀取組態設定檔
  profiles:
    validate: false
    active: '@xxxx@'

  # 資料庫連線設定
  datasource:
    url: jdbc:sqlserver://localhost:9433;database=java;encrypt=true;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # Spring Data JPA 設定
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  #Jackson
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Taipei
